'use strict';
// UI prototype only: transports, emergency broadcasts, authentication and cloud sync are simulated.
const $ = (selector, root = document) => root.querySelector(selector);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
  shield:'M12 3 3.8 6.5v5.8c0 4.8 4.1 7.5 8.2 9.7 4.1-2.2 8.2-4.9 8.2-9.7V6.5L12 3Z',
  plus:'M12 5v14M5 12h14', home:'m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9',
  radar:'M20 12a8 8 0 1 1-8-8M16 12a4 4 0 1 1-4-4M12 12l8-8',
  chat:'M21 11a8 8 0 0 1-8 8H6l-4 3 1-7a8 8 0 1 1 18-4ZM7 10h10M7 14h6',
  alert:'m12 3 10 18H2L12 3ZM12 9v5M12 17v.1',
  queue:'M8 6h13M8 12h13M8 18h8M3 6h.1M3 12h.1M3 18h.1',
  user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-2a8 8 0 0 1 16 0v2',
  people:'M15 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM5 21v-3a7 7 0 0 1 14 0v3M18 4a3 3 0 0 1 0 6M21 15v6',
  check:'m5 12 4 4L19 6', double:'m2 12 4 4L16 6m-5 9 2 2 9-11',
  arrow:'m9 5 7 7-7 7', back:'m15 5-7 7 7 7', down:'m6 9 6 6 6-6',
  bell:'M18 8a6 6 0 0 0-12 0c0 8-3 8-3 10h18c0-2-3-2-3-10M10 22h4',
  wifi:'M2 8a17 17 0 0 1 20 0M5 12a12 12 0 0 1 14 0M8 16a6 6 0 0 1 8 0M12 20h.1',
  offline:'m3 3 18 18M2 8a17 17 0 0 1 4-2M10 5a17 17 0 0 1 12 3M5 12a12 12 0 0 1 4-2M14 10a12 12 0 0 1 5 2M8 16a6 6 0 0 1 8 0M12 20h.1',
  bluetooth:'m7 7 10 10-5 4V3l5 4L7 17',
  location:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0ZM14 10a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z',
  clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',
  refresh:'M20 7a9 9 0 1 0 1 9M20 3v5h-5',
  cloud:'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5 5 0 0 1 0 11H6Z',
  network:'M12 4v5M5 13v-4h14v4M3 14h4v6H3ZM10 14h4v6h-4ZM17 14h4v6h-4ZM10 2h4v3h-4Z',
  sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M5 19l1-1M18 6l1-1',
  moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',
  send:'m3 3 19 9-19 9 4-9-4-9ZM7 12h15',
  clip:'m8 12 7-7a4 4 0 0 1 6 6L10 22a6 6 0 0 1-8-8L13 3m-8 14 9-9a2 2 0 0 1 3 3l-9 9',
  info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 11v6M12 7v.1',
  settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z',
  heart:'M12 21 3 12C-3 5 7-1 12 6c5-7 15-1 9 6l-9 9Z',
  eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
  download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
  logout:'M9 3H3v18h6M10 12h11m-5-5 5 5-5 5',
  phone:'M6 3H3v5c1 7 6 12 13 13h5v-4l-5-2-2 2c-4-2-6-4-7-7l2-2-3-5Z',
  x:'m6 6 12 12M6 18 18 6', image:'M3 3h18v18H3ZM3 17l6-7 5 5 3-3 4 5M16 7h.1',
  leaf:'M20 3C6 1 1 10 7 16c5 5 14 0 13-13ZM4 21 15 10',
};
function icon(name, cls = '') { return `<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${window.RESCUE_ICONS?.[name] || `<path d="${paths[name] || paths.info}"/>`}</svg>`; }
function badge(text, color = '', glyph = '') { return `<span class="pill ${color}">${glyph ? icon(glyph) : ''}${text}</span>`; }
function button(text, action, cls = '', glyph = '', extras = '') { return `<button class="btn ${cls}" data-action="${action}" ${extras}>${glyph ? icon(glyph) : ''}${text}</button>`; }
function empty(title, detail, glyph = 'radar') { return `<div class="empty">${icon(glyph)}<h3>${title}</h3><p class="small">${detail}</p></div>`; }
const seedPeers = [
  {id:'p1',name:'คุณมะลิ',initial:'ม',role:'sos',distance:85,seen:'เมื่อสักครู่',description:'ต้องการน้ำดื่มและอาหาร • มีผู้สูงอายุ',status:'ต้องการความช่วยเหลือ'},
  {id:'p2',name:'ทีมกู้ภัยอาสา 01',initial:'ก',role:'rescuer',distance:120,seen:'เมื่อสักครู่',description:'พร้อมช่วยเหลือ • อุปกรณ์ปฐมพยาบาล',status:'หน่วยกู้ภัย'},
  {id:'p3',name:'คุณนนท์',initial:'น',role:'user',distance:160,seen:'1 นาทีที่แล้ว',description:'เชื่อมต่อผ่าน RescueLink',status:'ผู้ใช้ทั่วไป'},
  {id:'p4',name:'ทีมกู้ภัยอาสา 02',initial:'ก',role:'rescuer',distance:240,seen:'2 นาทีที่แล้ว',description:'พร้อมช่วยเหลือ • รถขนส่ง',status:'หน่วยกู้ภัย'},
  {id:'p5',name:'คุณอรุณ',initial:'อ',role:'sos',distance:310,seen:'2 นาทีที่แล้ว',description:'ต้องการความช่วยเหลือในการเดินทาง',status:'ต้องการความช่วยเหลือ'},
  {id:'p6',name:'คุณพิม',initial:'พ',role:'user',distance:420,seen:'3 นาทีที่แล้ว',description:'เชื่อมต่อผ่าน RescueLink',status:'ผู้ใช้ทั่วไป'},
];
const seedMessages = [
  {id:'m1',peer:'p2',mine:false,text:'สวัสดีครับ ทีมกู้ภัยอาสาพร้อมช่วยเหลือ มีอะไรให้เราช่วยไหมครับ?',time:'10:24',status:'delivered',hops:0},
  {id:'m2',peer:'p2',mine:true,text:'ตอนนี้ปลอดภัยค่ะ อยู่บริเวณศูนย์พักพิง ต้องการน้ำดื่มเพิ่มประมาณ 10 ขวดค่ะ',time:'10:25',status:'delivered',hops:0},
  {id:'m3',peer:'p2',mine:false,text:'รับทราบครับ เรากำลังนำของเข้าไปให้ รอในพื้นที่ปลอดภัยได้เลยครับ',time:'10:26',status:'delivered',hops:0},
  {id:'m4',peer:'p2',mine:true,text:'ขอบคุณมากค่ะ 🙏',time:'10:27',status:'pending',hops:0},
  {id:'m5',peer:'p1',mine:true,text:'แจ้งทีมกู้ภัยให้แล้วนะคะ รอในที่ปลอดภัยก่อนค่ะ',time:'10:21',status:'pending',hops:2},
  {id:'m6',peer:'p3',mine:true,text:'จุดรับของอยู่ที่ศาลาชุมชนนะคะ',time:'09:58',status:'synced',hops:1},
];
const storageKey = 'rescuelink-ui-preview-v1';
let saved = {};
try { saved = JSON.parse(localStorage.getItem(storageKey) || '{}'); } catch { /* private mode or old state */ }
const state = {
  route:'home', filter:'all', rescuerFilter:'all', scenario:'normal', network:'adhoc', selected:'p2', onboard:0,
  theme:saved.theme === 'dark' ? 'dark' : 'light', sos:false, rescuer:!!saved.rescuer,
  profile:{name:'คุณพิมพ์',email:'',contact:'',blood:'ไม่ระบุ',medical:'',share:false,...saved.profile},
  messages:Array.isArray(saved.messages) ? saved.messages.filter(m => typeof m.text === 'string' && seedPeers.some(p=>p.id === m.peer)) : structuredClone(seedMessages),
  loggedIn:!!saved.loggedIn, logs:['เริ่มต้นพื้นที่สาธิต RescueLink','โหลดข้อความจากพื้นที่เก็บข้อมูลบนเครื่อง'],
  syncHistory:[], busy:false, scanning:false, permissions:false, drafts:{},
};
const routeNames = {home:'อุปกรณ์ใกล้เคียง',sos:'ขอความช่วยเหลือ',rescuer:'โหมดหน่วยกู้ภัย',chat:'การสนทนา',queue:'คิวข้อความ',network:'สถานะเครือข่าย',settings:'โปรไฟล์และตั้งค่า',splash:'ยินดีต้อนรับ',onboarding:'รู้จัก RescueLink',auth:'บัญชีผู้ใช้'};
const navItems = [['home','radar','อุปกรณ์ใกล้เคียง'],['chat','chat','ข้อความ'],['sos','alert','ขอความช่วยเหลือ'],['rescuer','shield','หน่วยกู้ภัย'],['queue','queue','คิวข้อความ'],['network','network','เครือข่าย'],['settings','settings','ตั้งค่า']];
let toastTimer, holdTimer, deferredInstall;
function persist() {
  try {
    localStorage.setItem(storageKey, JSON.stringify({theme:state.theme,rescuer:state.rescuer,profile:state.profile,loggedIn:state.loggedIn,messages:state.messages.filter(m=>!m.attachment).slice(-150)}));
  } catch { toast('พื้นที่เก็บข้อมูลเต็ม — การเปลี่ยนแปลงครั้งนี้จะอยู่เฉพาะตอนเปิดหน้าเว็บ'); }
}
function toast(text) { const t=$('#toast'); t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),4000); }
function log(text) {state.logs.push(`${new Date().toLocaleTimeString('th-TH',{hour12:false})}  ${text}`);state.logs=state.logs.slice(-60);}
function navigate(route) { cancelHold();state.route=route;location.hash=route;render();window.scrollTo({top:0,behavior:'instant'}); }
function getPeers() { return state.scenario==='empty' ? [] : seedPeers.filter(p=>state.filter==='all' || p.role===state.filter); }
function pendingCount() {return state.messages.filter(m=>m.mine && m.status==='pending').length;}
function networkLabel() {return state.network==='online' ? 'Online · จำลองอินเทอร์เน็ต' : state.network==='adhoc' ? `Ad-hoc · ${state.scenario==='empty'?0:6} อุปกรณ์ใกล้เคียง` : 'Offline · เก็บข้อความไว้ในเครื่อง';}
function peerCard(peer) {
  const color = peer.role==='sos'?'red':peer.role==='rescuer'?'blue':'neutral';
  return `<button class="device" data-action="chat:${peer.id}" aria-label="สนทนากับ ${escapeHtml(peer.name)}"><span class="avatar ${color}">${peer.role==='rescuer'?icon('shield'):peer.initial}</span><span class="grow"><span class="title-row"><h3>${peer.name}</h3>${badge(peer.role==='sos'?'SOS':peer.role==='rescuer'?'กู้ภัย':'ทั่วไป',color,peer.role==='sos'?'alert':peer.role==='rescuer'?'check':'user')}</span><p>${peer.description}</p></span><span class="device-meta"><strong>${peer.distance} ม.</strong>${peer.seen}</span>${icon('arrow','arrow')}</button>`;
}
function intro(title, sub, eyebrow = 'RESCUELINK / COMMUNITY', action = '') {return `<section class="intro"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div>${action}</section>`;}
function simulationControls() {return `<div class="preview-toolbar">${icon('eye')}<span>ทดลองสถานการณ์</span><select id="scenario" aria-label="เลือกสถานการณ์จำลอง"><option value="normal" ${state.scenario==='normal'?'selected':''}>ข้อมูลปกติ</option><option value="empty" ${state.scenario==='empty'?'selected':''}>ไม่พบอุปกรณ์</option><option value="error" ${state.scenario==='error'?'selected':''}>สิทธิ์ไม่พร้อม</option></select><span class="small">ระยะทาง พิกัด และสถานะเป็นข้อมูลจำลอง</span></div>`;}
function home() {
  const peers = getPeers();
  return `${intro(`สวัสดี, ${escapeHtml(state.profile.name)} <span style="font-weight:400">☀</span>`,'อยู่ใกล้กัน อุ่นใจกว่า · เชื่อมต่อได้แม้ไม่มีอินเทอร์เน็ต','YOUR NEIGHBORHOOD, CONNECTED',button(state.scanning?'กำลังค้นหา…':'ค้นหาอีกครั้ง','scan','', 'refresh',state.scanning?'disabled':''))}
  <div class="two-column"><div>
    <div class="hero"><div><span class="pill orange">${icon('shield')} เชื่อมต่อความอุ่นใจ</span><h2 style="margin-top:14px">สัญญาณอาจหาย<br>แต่ความช่วยเหลือยังอยู่ใกล้</h2><p>ส่งข้อความถึงคนใกล้ตัวและทีมกู้ภัย<br>ผ่านเครือข่ายระหว่างอุปกรณ์</p>${button('เริ่มสนทนา','chat:p2','primary','chat')}</div><div class="hero-art" aria-hidden="true"><div class="hero-shield">${icon('plus')}</div><div class="float-note">${icon('check')} อยู่เคียงข้างคุณ</div></div></div>
    <div class="stats"><div class="stat"><div class="row">${icon('people')}อุปกรณ์ใกล้เคียง</div><strong>${state.scenario==='empty'?0:6}<small class="muted"> เครื่อง</small></strong></div><div class="stat"><div class="row">${icon('shield')}หน่วยกู้ภัย</div><strong style="color:var(--blue-ink)">${state.scenario==='empty'?0:2}<small class="muted"> ทีม</small></strong></div><div class="stat"><div class="row">${icon('clock')}ข้อความค้างส่ง</div><strong style="color:var(--yellow-ink)">${pendingCount()}<small class="muted"> ข้อความ</small></strong></div></div>
    <div class="section-head"><h2>คนใกล้ตัว พร้อมเชื่อมต่อ</h2>${badge('อัปเดตล่าสุด · ตอนนี้','green','refresh')}</div>
    <div class="tabs" role="group" aria-label="กรองอุปกรณ์">${[['all','ทั้งหมด','6'],['sos','ขอความช่วยเหลือ','2'],['rescuer','หน่วยกู้ภัย','2'],['user','ทั่วไป','2']].map(([key,label,count])=>`<button class="tab ${state.filter===key?'active':''}" data-action="filter:${key}" aria-pressed="${state.filter===key}">${label} · ${state.scenario==='empty'?0:count}</button>`).join('')}</div>
    ${state.scenario==='error'?`<div class="note" style="color:var(--danger-ink)">${icon('alert')}<div><h3>ยังค้นหาอุปกรณ์ไม่ได้</h3><p>อนุญาต Bluetooth และอุปกรณ์ใกล้เคียง แล้วลองอีกครั้ง</p>${button('ตรวจสอบสิทธิ์','permissions','soft','settings')}</div></div>`:state.scanning?'<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>':peers.length?peers.map(peerCard).join(''):empty('ยังไม่พบคนใกล้ตัว','เปิดให้อีกเครื่องค้นพบ แล้วลองค้นหาอีกครั้ง')}
    ${simulationControls()}
  </div><aside class="stack home-side">
    <div class="card radar-card"><div class="row between"><h3>มองเห็นความช่วยเหลือรอบตัว</h3>${badge('จำลอง','orange')}</div><p class="small muted" style="margin-top:5px">เรดาร์อุปกรณ์ในบริเวณใกล้เคียง</p><div class="radar" aria-label="แผนภาพตำแหน่งจำลอง"><div class="radar-center">${icon('user')}</div>${state.scenario==='empty'?'':`<button class="node red" style="left:25%;top:20%" data-action="chat:p1" aria-label="คุณมะลิ ขอความช่วยเหลือ"><span>85 ม.</span></button><button class="node" style="right:14%;top:28%" data-action="chat:p2" aria-label="ทีมกู้ภัยอาสา 01"><span>120 ม.</span></button><button class="node gray" style="left:15%;bottom:17%" data-action="chat:p3" aria-label="คุณนนท์"><span>160 ม.</span></button><button class="node" style="right:22%;bottom:8%" data-action="chat:p4" aria-label="ทีมกู้ภัยอาสา 02"><span>240 ม.</span></button>`}</div><div class="radar-legend"><span><i class="legend-mark" style="background:var(--danger)"></i>SOS</span><span><i class="legend-mark" style="background:var(--blue)"></i>หน่วยกู้ภัย</span><span><i class="legend-mark" style="background:#958b82"></i>ทั่วไป</span></div><p class="small muted center">ระยะเป็นข้อมูลตัวอย่าง ไม่ใช่ตำแหน่งจริง</p></div>
    <div class="sos-mini"><div class="row">${icon('alert')}<h3>ต้องการความช่วยเหลือ?</h3></div><p>ทดลองแจ้งข้อความสั้นและพิกัดให้คนใกล้เคียง<br>กดค้างเพื่อยืนยัน ป้องกันการกดโดยไม่ตั้งใจ</p>${button('ไปที่หน้าขอความช่วยเหลือ','nav:sos','full','arrow')}</div>
    <div class="card"><div class="row between"><h3>การสนทนาล่าสุด</h3><button class="text-link" data-action="nav:chat">ดูทั้งหมด</button></div>${['p2','p1'].map(id=>{const p=seedPeers.find(p=>p.id===id);const m=state.messages.filter(m=>m.peer===id).at(-1);return `<button class="recent" data-action="chat:${id}"><span class="avatar ${p.role==='sos'?'red':'blue'}">${p.initial}</span><span class="grow"><h3 style="font-size:13px">${p.name}</h3><p>${escapeHtml((m?.text||'เริ่มสนทนา').slice(0,30))}${m?.text.length>30?'…':''}</p></span>${icon('arrow','arrow')}</button>`}).join('')}</div>
    <div class="note">${icon('leaf')}<span>ข้อความถูกเก็บในเครื่องก่อนเสมอ<br>เมื่อเชื่อมต่อได้ ระบบจำลองจะส่งต่อให้คุณ</span></div>
  </aside></div>`;
}
function sosPage() {return `${intro('ให้คนใกล้ตัวช่วยคุณ','บอกสิ่งที่ต้องการสั้น ๆ แล้วกดค้างเพื่อยืนยัน','EMERGENCY / SOS')}
  <div class="two-column"><div class="card center"><span class="pill red">${icon('info')} โหมดสาธิต · ไม่ส่งสัญญาณขอความช่วยเหลือจริง</span><div class="sos-stage"><button id="sos-hold" class="sos-hold ${state.sos?'active':''}" aria-label="${state.sos?'ปิด SOS จำลอง':'กดค้าง 2 วินาทีเพื่อเปิด SOS จำลอง'}"><strong>${state.sos?'หยุด':'SOS'}</strong><small>${state.sos?'แตะเพื่อปิดการจำลอง':'กดค้าง 2 วินาที'}</small></button></div><div class="progress-track"><div id="hold-progress" class="progress-fill"></div></div><h2>${state.sos?'กำลังจำลองการกระจาย SOS':'ขอความช่วยเหลือได้ใน 2 แตะ'}</h2><p class="muted small" style="margin:8px 0 24px">${state.sos?'สถานะนี้แสดงบนหน้าจอต้นแบบเท่านั้น':'ใช้เมาส์ นิ้ว หรือกด Space ค้างบนปุ่ม'}</p><label class="field" style="text-align:left">คุณต้องการความช่วยเหลือเรื่องอะไร?<textarea id="sos-text" class="input" maxlength="200" rows="3" placeholder="เช่น ต้องการน้ำดื่ม มีผู้สูงอายุ 1 คน">${escapeHtml(state.sosText||'ต้องการน้ำดื่มและอาหาร อยู่บริเวณศูนย์พักพิง')}</textarea></label><div class="coordinate"><div style="text-align:left"><div class="row">${icon('location')}<strong>พิกัดตัวอย่าง</strong></div><p class="small muted">14.0368, 100.7279 · อัปเดตจำลอง 1 นาทีที่แล้ว</p></div>${badge('ไม่ใช่ GPS จริง','yellow')}</div></div><div class="stack"><div class="card"><h3>สถานะการกระจายสัญญาณ</h3><div class="setting"><span>สถานะ SOS</span>${badge(state.sos?'เปิดจำลอง':'ยังไม่เปิด',state.sos?'red':'',state.sos?'alert':'shield')}</div><div class="setting"><span>อุปกรณ์ที่รับได้ (จำลอง)</span><strong>${state.sos&&state.network!=='offline'?'4 / 6':'0 / 6'} เครื่อง</strong></div><div class="setting"><span>ข้อมูลที่แนบ</span><span class="small muted">ข้อความ + พิกัดตัวอย่าง</span></div></div><div class="note">${icon('info')}<div><strong>ก่อนทดสอบบนเครื่องจริง</strong><p>Phase 2 รองรับข้อความและ ACK เท่านั้น การส่ง SOS, GPS และแจ้งเตือนเครื่องอื่นยังต้องพัฒนาเพิ่มเติม</p></div></div>${button('ดูหน้าจอหน่วยกู้ภัย','nav:rescuer','soft','shield')}</div></div>`;}
function rescuerPage(){const peers=seedPeers.filter(p=>p.role==='sos'&&(state.rescuerFilter!=='near'||p.distance<200));return `${intro('อยู่ใกล้ พร้อมช่วยเหลือ','มองเห็นคำขอความช่วยเหลือและเริ่มประสานงาน','RESCUER / COMMUNITY CARE')}
  <div class="card row between" style="background:var(--blue-bg);margin-bottom:24px"><div class="row"><span class="avatar blue">${icon('shield')}</span><div><h2 style="color:var(--blue-ink)">โหมดหน่วยกู้ภัย</h2><p class="small muted">สถานะจำลอง · ไม่ยืนยันสิทธิ์หรือส่งสถานะให้อุปกรณ์อื่น</p></div></div><button class="toggle" role="switch" aria-checked="${state.rescuer}" aria-label="โหมดหน่วยกู้ภัยจำลอง" data-action="toggle:rescuer"></button></div>
  <div class="section-head"><h2>คำขอความช่วยเหลือใกล้คุณ</h2>${badge('2 รายการตัวอย่าง','red','alert')}</div><div class="tabs"><button class="tab ${state.rescuerFilter==='all'?'active':''}" data-action="rescuer-filter:all">เร่งด่วนและใกล้ที่สุด</button><button class="tab ${state.rescuerFilter==='near'?'active':''}" data-action="rescuer-filter:near">ระยะน้อยกว่า 200 ม.</button></div>${peers.map(peerCard).join('')}<div class="note" style="margin-top:24px">${icon('info')}ระยะทางและความเร่งด่วนเป็นตัวอย่างสำหรับออกแบบหน้าจอ ไม่ควรใช้ตัดสินใจช่วยเหลือจริง</div>`;}
const statusText={pending:'ค้างส่ง',sent:'ส่งแล้ว',delivered:'ถึงปลายทางแล้ว',synced:'ซิงก์แล้ว (จำลอง)'};
const statusIcon={pending:'clock',sent:'check',delivered:'double',synced:'cloud'};
function chatPage(){const peer=seedPeers.find(p=>p.id===state.selected)||seedPeers[1];const messages=state.messages.filter(m=>m.peer===peer.id);return `<div class="chat-page">${intro('ข้อความถึงคนใกล้ตัว','บันทึกในเครื่องก่อน ส่งต่อเมื่อเชื่อมต่อได้','MESSAGES / OFFLINE FIRST',button('ดูคิวส่ง','nav:queue','','queue'))}<div class="chat-layout"><aside class="card chat-list"><h3 style="margin-bottom:12px">การสนทนา</h3>${seedPeers.slice(0,4).map(p=>`<button class="recent" data-action="chat:${p.id}"><span class="avatar ${p.role==='rescuer'?'blue':p.role==='sos'?'red':''}">${p.initial}</span><span class="grow"><h3 style="font-size:13px">${p.name}</h3><p>${p.status}</p></span></button>`).join('')}</aside><section class="chat-panel"><div class="chat-header row"><span class="avatar ${peer.role==='rescuer'?'blue':peer.role==='sos'?'red':''}">${peer.initial}</span><div class="grow"><h3>${peer.name}</h3><div class="small muted">${state.network==='offline'?'ออฟไลน์ · ข้อความจะเข้าคิว':'เชื่อมต่อจำลอง · Nearby Connections'}</div></div>${badge('DEMO','orange')}</div><div class="messages" id="messages"><div class="day-separator">วันนี้ · การสนทนาตัวอย่าง</div>${messages.length?messages.map(m=>`<div class="bubble-wrap ${m.mine?'mine':''}"><div class="bubble">${m.attachment ? m.attachment.type==='image'?`<img src="${m.attachment.url}" alt="ภาพตัวอย่างก่อนส่ง">`:`<video src="${m.attachment.url}" controls preload="metadata"></video>`:''}${escapeHtml(m.text)}</div><div class="bubble-meta"><span>${escapeHtml(m.time)}</span>${m.mine?icon(statusIcon[m.status]||'clock')+'<span>'+statusText[m.status]+'</span>':''}${m.hops?`<span>· ${m.hops} hops ผ่านทีมอาสา (จำลอง)</span>`:''}</div></div>`).join(''):empty('เริ่มต้นด้วยคำทักทาย','ข้อความทดลองจะเก็บในเบราว์เซอร์เครื่องนี้','chat')}</div><form id="chat-form" class="chat-composer"><button type="button" class="btn ghost" data-action="attach" aria-label="แนบรูปภาพหรือวิดีโอ">${icon('clip')}</button><textarea id="chat-input" class="input grow" rows="1" maxlength="2000" placeholder="พิมพ์ข้อความที่นี่…" aria-label="ข้อความ"></textarea><button class="btn primary" type="submit" aria-label="ส่งข้อความจำลอง">${icon('send')}</button><input id="attachment" type="file" accept="image/*,video/*" class="hidden"></form><div class="small muted center" style="padding:0 12px 12px">ข้อความและสื่อในหน้านี้ไม่ได้ส่งออกไปหาอุปกรณ์จริง</div></section></div></div>`;}
function queuePage(){const pending=state.messages.filter(m=>m.mine&&m.status==='pending');const sent=state.messages.filter(m=>m.mine&&['sent','delivered'].includes(m.status));const synced=state.messages.filter(m=>m.mine&&m.status==='synced');return `${intro('ข้อความของคุณ ไม่หายไปไหน','ดูคิวค้างส่ง และลองจำลองการซิงก์เมื่อกลับมาออนไลน์','QUEUE / SYNC CENTER')}
  <div class="metric-grid"><div class="metric"><span class="small muted">รอส่ง</span><strong style="color:var(--yellow-ink)">${pending.length}</strong></div><div class="metric"><span class="small muted">ส่งแล้ว / ถึงแล้ว</span><strong>${sent.length}</strong></div><div class="metric"><span class="small muted">ซิงก์จำลอง</span><strong style="color:var(--success-ink)">${synced.length}</strong></div></div><div class="section-head"><h2>คิวข้อความ</h2>${button(state.busy?'กำลังดำเนินการ…':'ลองส่งอีกครั้ง','retry','','refresh',state.busy?'disabled':'')}</div><div class="card">${pending.length?pending.map(m=>`<div class="queue-row"><div class="row between"><h3>${seedPeers.find(p=>p.id===m.peer)?.name}</h3>${badge('ค้างส่ง','yellow','clock')}</div><p>${escapeHtml(m.text)}</p><span class="small muted">${m.time} · เก็บไว้ในเครื่องแล้ว ${m.hops?'· ส่งต่อหลายทอด (จำลอง)':''}</span></div>`).join(''):empty('ไม่มีข้อความค้างส่ง','ข้อความทั้งหมดอยู่ในสถานะส่งแล้วหรือซิงก์จำลอง','check')}</div><div class="card" style="margin-top:24px"><div class="row between wrap"><div><h3>พร้อมเมื่อกลับมาออนไลน์</h3><p class="small muted">จำลองการซิงก์ได้เมื่อเลือกเครือข่าย Online</p></div>${button('ซิงก์จำลอง','sync','primary','cloud',state.busy?'disabled':'')}</div>${state.syncHistory.length?`<div style="margin-top:16px">${state.syncHistory.map(s=>`<p class="log">${escapeHtml(s)}</p>`).join('')}</div>`:''}</div><div class="note" style="margin-top:20px">${icon('info')}ยังไม่มีคลาวด์หรือบัญชีจริงเชื่อมต่อ การซิงก์เปลี่ยนสถานะตัวอย่างบนเครื่องนี้เท่านั้น</div>`;}
function networkPage(){return `${intro('เห็นทุกการเชื่อมต่อ','แผงสาธิตเครือข่าย สำหรับตรวจลำดับการทำงาน','NETWORK / DEBUG')}
  <div class="two-column"><div class="stack"><div class="card"><h2>เลือกเครือข่ายจำลอง</h2><p class="small muted" style="margin:8px 0 20px">ไม่เปลี่ยน Wi-Fi หรือ Bluetooth ของเครื่องจริง</p><div class="stack">${[['adhoc','bluetooth','Ad-hoc','เชื่อมต่อกับอุปกรณ์ใกล้เคียง ไม่มีอินเทอร์เน็ต'],['offline','offline','Offline','ไม่มีการเชื่อมต่อ เก็บข้อความเข้าคิว'],['online','wifi','Online','ส่งข้อความและจำลองการซิงก์คลาวด์']].map(([key,glyph,label,sub])=>`<button class="device" style="margin:0;${state.network===key?'border-color:var(--primary-dark);background:var(--primary-light)':''}" data-action="network:${key}" aria-pressed="${state.network===key}"><span class="avatar">${icon(glyph)}</span><span class="grow"><h3>${label}</h3><p>${sub}</p></span>${state.network===key?icon('check'):''}</button>`).join('')}</div></div><div class="card"><div class="row between"><h3>บันทึกการทำงานจำลอง</h3>${button('ล้าง','clear-log','ghost')}</div>${state.logs.map(l=>`<div class="log">${escapeHtml(l)}</div>`).reverse().join('')}</div></div><div class="stack"><div class="card"><h3>ข้อมูลสำหรับการสาธิต</h3><div class="setting"><span>โปรโตคอลที่ออกแบบไว้</span><strong class="small">Nearby Connections</strong></div><div class="setting"><span>การรับส่งของเว็บนี้</span>${badge('ไม่มี transport จริง','yellow')}</div><div class="setting"><span>อุปกรณ์ตัวอย่าง</span><strong>6 nodes</strong></div><div class="setting"><span>การส่งต่อหลายทอด</span><strong class="small">ตัวอย่าง 0–2 hops</strong></div><div class="setting"><span>เบราว์เซอร์รายงานเน็ต</span>${badge(navigator.onLine?'Online':'Offline',navigator.onLine?'green':'yellow')}</div><div class="setting"><span>แคชออฟไลน์ PWA</span><span id="sw-status" class="small muted">${'serviceWorker' in navigator?'กำลังตรวจสอบ':'เบราว์เซอร์ไม่รองรับ'}</span></div></div><div class="note">${icon('info')}การทดสอบ 2 เครื่องจริงให้ใช้แอป Flutter Phase 2 เว็บนี้มีไว้ตรวจ UI/UX เท่านั้น</div></div></div>`;}
function settingsPage(){return `${intro('ปรับให้เป็นคุณ','ข้อมูลและการตั้งค่าบันทึกเฉพาะในเบราว์เซอร์เครื่องนี้','PROFILE / SETTINGS')}
  <div class="two-column"><form id="profile-form" class="card"><div class="row" style="margin-bottom:24px"><span class="avatar" style="width:64px;height:64px;font-size:25px">${escapeHtml(Array.from(state.profile.name)[0]||'พ')}</span><div><h2>${escapeHtml(state.profile.name)}</h2>${badge(state.loggedIn?'บัญชีจำลอง':'ผู้ใช้โหมดสาธิต','orange','user')}</div></div><label class="field">ชื่อที่แสดง<input class="input" name="name" required maxlength="32" value="${escapeHtml(state.profile.name)}"></label><label class="field">เบอร์ติดต่อฉุกเฉิน <small>(ไม่บังคับ)</small><input class="input" name="contact" type="tel" maxlength="30" placeholder="กรอกข้อมูลตัวอย่างเท่านั้น" value="${escapeHtml(state.profile.contact)}"></label><label class="field">กรุ๊ปเลือด<select class="input" name="blood">${['ไม่ระบุ','A','B','AB','O'].map(v=>`<option ${state.profile.blood===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">ข้อมูลสุขภาพ <small>(ข้อมูลตัวอย่างเท่านั้น)</small><textarea class="input" name="medical" rows="2" maxlength="200" placeholder="เช่น แพ้ยา…">${escapeHtml(state.profile.medical)}</textarea></label><label class="row small" style="margin-bottom:24px"><input type="checkbox" name="share" ${state.profile.share?'checked':''} style="width:24px;height:24px;accent-color:var(--primary-dark)">แสดงข้อมูลสุขภาพในการ์ด SOS จำลอง</label>${button('บันทึกข้อมูล','save-profile','primary full','check','type="submit"')}<p class="small muted" style="margin-top:12px">ไม่ควรใส่ข้อมูลส่วนตัวหรือข้อมูลสุขภาพจริงในต้นแบบ</p></form><div class="stack"><div class="card"><h3>การแสดงผล</h3><div class="setting"><div><h3>โหมดมืด</h3><p>ส้มอบอุ่นบนพื้นหลังน้ำตาลเข้ม</p></div><button class="toggle" role="switch" aria-checked="${state.theme==='dark'}" aria-label="โหมดมืด" data-action="theme"></button></div><div class="setting"><div><h3>ภาษา</h3><p>ภาษาไทย · English อยู่ในแผนพัฒนา</p></div>${badge('ไทย','orange')}</div><div class="setting"><div><h3>สิทธิ์การเข้าถึง</h3><p>Bluetooth / Nearby / ตำแหน่ง</p></div><button class="icon-btn" data-action="permissions" aria-label="ดูสิทธิ์">${icon('arrow')}</button></div></div><div class="card stack"><h3>พื้นที่สาธิต</h3>${button('ดูวิธีใช้งาน 3 ขั้นตอน','nav:onboarding','','info')}${button(state.loggedIn?'ออกจากบัญชีจำลอง':'เข้าสู่ระบบ / สมัครจำลอง',state.loggedIn?'logout':'nav:auth','','user')}${button('ติดตั้งต้นแบบ','install','install-btn'+(deferredInstall?' available':''),'download')}${button('รีเซ็ตข้อมูลตัวอย่าง','reset','ghost','refresh')}</div><div class="note">${icon('shield')}ไม่มีข้อมูลถูกส่งออกจากเครื่อง การล้างข้อมูลเว็บไซต์จะลบประวัติจำลองและการตั้งค่า</div></div></div>`;}
function onboarding(){const slides=[['shield','อุ่นใจ แม้ไร้สัญญาณ','RescueLink ช่วยให้คุณติดต่อคนใกล้ตัวและทีมกู้ภัย ในวันที่อินเทอร์เน็ตเข้าไม่ถึง'],['bluetooth','เปิดทางให้เราเชื่อมถึงกัน','แอปจริงต้องใช้ Bluetooth, อุปกรณ์ใกล้เคียง และบริการตำแหน่งตามรุ่น Android เพื่อค้นหาอุปกรณ์'],['chat','ค้นหา เชื่อมต่อ แล้วเริ่มคุย','ค้นหาอุปกรณ์ใกล้เคียง เลือกคู่สนทนา แล้วส่งข้อความ ข้อความจะบันทึกในเครื่องก่อนเสมอ']];const [glyph,title,text]=slides[state.onboard];return `<div class="onboarding center"><div class="row between"><span class="eyebrow">WELCOME TO RESCUELINK</span><button class="text-link" data-action="nav:home">ข้าม</button></div><div class="onboard-art">${icon(glyph)}</div><h1>${title}</h1><p>${text}</p><div class="step-dots" aria-label="ขั้นตอน ${state.onboard+1} จาก 3">${slides.map((_,i)=>`<span class="${i===state.onboard?'active':''}"></span>`).join('')}</div>${button(state.onboard===2?'พร้อมแล้ว เริ่มใช้งาน':'ถัดไป','onboard-next','primary full','arrow')}${state.onboard>0?button('ย้อนกลับ','onboard-back','ghost full'):''}<p class="small">ต้นแบบ UI · ข้อมูลและการเชื่อมต่อทั้งหมดเป็นการจำลอง</p></div>`;}
function authPage(){return `<div class="onboarding"><div class="center"><span class="avatar" style="margin:12px auto 24px;width:72px;height:72px">${icon('user')}</span><span class="eyebrow">A PLACE TO CONNECT</span><h1 style="margin-top:8px">ยินดีที่ได้รู้จัก</h1><p>สร้างโปรไฟล์ตัวอย่างเพื่อทดลองประสบการณ์สมาชิก</p></div><form id="auth-form" class="card"><label class="field">ชื่อที่แสดง<input name="name" class="input" required maxlength="32" placeholder="คุณอยากให้เราเรียกว่าอะไร"></label><label class="field">อีเมลตัวอย่าง<input name="email" type="email" class="input" required placeholder="name@example.com"></label><div class="note" style="margin-bottom:20px">${icon('info')}ไม่มีการยืนยันตัวตนหรือเชื่อมคลาวด์ ไม่ต้องใช้รหัสผ่านจริง</div><button class="btn primary full" type="submit">เข้าสู่ระบบ / สมัครแบบจำลอง ${icon('arrow')}</button></form>${button('สำรวจโดยไม่สร้างโปรไฟล์','nav:home','ghost full')}</div>`;}
function splashPage(){return `<div class="onboarding center"><div class="onboard-art"><img src="assets/icon-192.png" width="112" height="112" alt="โลโก้ RescueLink" style="border-radius:32px;box-shadow:0 12px 40px #e8772e25"></div><div class="eyebrow">CONNECTED BY CARE</div><h1 style="font-size:40px;margin-top:12px">RescueLink<span style="color:var(--primary-dark)">.</span></h1><p>อุ่นใจ แม้ไร้สัญญาณ<br>เพราะความช่วยเหลือเริ่มจากคนใกล้ตัว</p>${button('ทำความรู้จักกัน','nav:onboarding','primary full','arrow')}${button('สำรวจต้นแบบ','nav:home','ghost full')}<p class="small">พื้นที่สาธิต UI · ไม่ใช่ระบบแจ้งเหตุจริง</p></div>`;}
function render(){
  const activeId=document.activeElement?.id;
  const caret=document.activeElement?.selectionStart;
  document.documentElement.dataset.theme=state.theme;
  $('meta[name="theme-color"]').content=state.theme==='dark'?'#191512':'#FFF8F2';
  const page={home,sos:sosPage,rescuer:rescuerPage,chat:chatPage,queue:queuePage,network:networkPage,settings:settingsPage,splash:splashPage,onboarding,auth:authPage}[state.route]||home;
  $('#app').innerHTML=`<aside class="sidebar"><div class="brand"><span class="brand-mark">${icon('shield')}</span><span>RescueLink<span style="color:var(--primary-dark)">.</span></span></div><p class="brand-sub">อุ่นใจ แม้ไร้สัญญาณ</p><nav class="side-nav" aria-label="เมนูหลัก">${navItems.map(([key,glyph,label])=>`<button data-action="nav:${key}" class="${state.route===key?'active':''}" ${state.route===key?'aria-current="page"':''} title="${label}">${icon(glyph)}<span class="nav-label">${label}</span>${key==='queue'&&pendingCount()?'<span class="pill orange nav-label">'+pendingCount()+'</span>':''}</button>`).join('')}</nav><div class="sidebar-footer"><div class="row"><span class="avatar">${escapeHtml(Array.from(state.profile.name)[0]||'พ')}</span><div><h3 style="font-size:13px">${escapeHtml(state.profile.name)}</h3><p class="small muted">${state.rescuer?'หน่วยกู้ภัยจำลอง':'ผู้ใช้โหมดสาธิต'}</p></div></div><div class="note" style="padding:12px;margin-top:20px">${icon('info')}ต้นแบบเท่านั้น<br>ไม่ใช่ระบบแจ้งเหตุจริง</div></div></aside><div class="main-shell"><header class="topbar"><div class="breadcrumb">RescueLink ${icon('arrow')} <span style="color:var(--ink)">${routeNames[state.route]}</span></div><div class="mobile-brand brand"><span class="brand-mark">${icon('shield')}</span>RescueLink<span style="color:var(--primary-dark)">.</span></div><div class="header-actions"><span class="demo-tag">INTERACTIVE PREVIEW</span><button class="icon-btn" data-action="theme" aria-label="${state.theme==='dark'?'เปิดโหมดสว่าง':'เปิดโหมดมืด'}">${icon(state.theme==='dark'?'sun':'moon')}</button><button class="icon-btn" data-action="notifications" aria-label="การแจ้งเตือน">${icon('bell')}</button><span class="avatar">${escapeHtml(Array.from(state.profile.name)[0]||'พ')}</span></div></header><div class="network-strip"><div class="row">${icon(state.network==='online'?'wifi':state.network==='adhoc'?'bluetooth':'offline')}<strong>${networkLabel()}</strong><span class="demo-tag">จำลอง</span></div><button data-action="nav:network">ดูเครือข่าย ${icon('arrow','arrow')}</button></div><main class="content" id="main-content">${page()}</main></div><nav class="bottom-nav" aria-label="เมนูหลักบนมือถือ">${[['home','radar','ใกล้ฉัน'],['chat','chat','ข้อความ'],['sos','alert','SOS'],['queue','queue','คิวส่ง'],['settings','user','ฉัน']].map(([key,glyph,label])=>`<button data-action="nav:${key}" class="${key==='sos'?'sos-nav ':''}${state.route===key?'active':''}" ${state.route===key?'aria-current="page"':''} aria-label="${routeNames[key]}">${key==='sos'?'SOS':icon(glyph)+`<span>${label}</span>`}</button>`).join('')}</nav>`;
  if(state.route==='sos'){
    bindHold();
    if(state.profile.share)document.querySelector('.two-column>.stack').insertAdjacentHTML('beforeend',`<div class="card"><h3>ข้อมูลเพิ่มเติมที่เลือกแชร์ (จำลอง)</h3><p class="small muted">กรุ๊ปเลือด: ${escapeHtml(state.profile.blood)}</p><p>${escapeHtml(state.profile.medical||'ไม่ระบุข้อมูลสุขภาพ')}</p></div>`);
  }
  if(state.route==='chat') {
    const box=$('#messages');box.scrollTop=box.scrollHeight;
    const input=$('#chat-input');input.value=state.drafts[state.selected]||'';
    if(activeId==='chat-input'){input.focus();if(typeof caret==='number')input.setSelectionRange(caret,caret);}
  }
  if(state.route==='network' && 'serviceWorker' in navigator) navigator.serviceWorker.getRegistration().then(r=>{const el=$('#sw-status');if(el)el.textContent=r?.active?'พร้อมใช้งาน':'เปิดผ่าน localhost / HTTPS';});
}
function modal(title,body,confirmText='เข้าใจแล้ว',onConfirm){const dialog=$('#modal');dialog.innerHTML=`<h2 id="dialog-title">${title}</h2><p>${body}</p><div class="row">${onConfirm?'<button class="btn ghost" id="dialog-cancel">ยกเลิก</button>':''}<button class="btn primary" id="dialog-confirm">${confirmText}</button></div>`;dialog.showModal();$('#dialog-cancel')?.addEventListener('click',()=>dialog.close());$('#dialog-confirm').addEventListener('click',()=>{dialog.close();onConfirm?.();});}
function cancelHold(){clearTimeout(holdTimer);holdTimer=null;const p=$('#hold-progress');if(p){p.style.transition='none';p.style.width='0';}$('#sos-hold')?.classList.remove('holding');}
function bindHold(){const b=$('#sos-hold');function start(event){if(event.type==='keydown' && ![' ','Enter'].includes(event.key))return;if(event.repeat)return;event.preventDefault();if(state.sos){state.sos=false;log('ปิด SOS จำลอง');render();toast('ปิด SOS จำลองแล้ว');return;}if(holdTimer)return;b.classList.add('holding');const p=$('#hold-progress');p.style.transition='width 2s linear';requestAnimationFrame(()=>p.style.width='100%');holdTimer=setTimeout(()=>{holdTimer=null;state.sos=true;state.sosText=$('#sos-text').value;log('เปิด SOS จำลอง (ไม่ได้ broadcast จริง)');render();toast('เปิด SOS จำลองแล้ว — ไม่มีการแจ้งเหตุจริง');},2000);}
  b.addEventListener('pointerdown',start);b.addEventListener('keydown',start);['pointerup','pointercancel','pointerleave','keyup','blur'].forEach(e=>b.addEventListener(e,cancelHold));
}
async function retryMessages(sync=false){if(state.busy)return;if(state.network==='offline'){toast('ยังออฟไลน์อยู่ เปลี่ยนเป็น Ad-hoc จำลองแล้วลองใหม่');return;}if(sync && state.network!=='online'){toast('เลือก Online ในหน้าเครือข่ายก่อนซิงก์จำลอง');return;}state.busy=true;render();await new Promise(r=>setTimeout(r,650));for(const m of state.messages){if(!m.mine)continue;if(sync)m.status='synced';else if(m.status==='pending')m.status='delivered';}state.busy=false;if(sync)state.syncHistory.unshift(new Date().toLocaleTimeString('th-TH')+' · จำลองการซิงก์สำเร็จ ไม่มีการอัปโหลดจริง');persist();log(sync?'ซิงก์ข้อความจำลองแล้ว':'ส่งคิวและรับ ACK จำลองแล้ว');render();toast(sync?'ซิงก์สถานะจำลองแล้ว':'ข้อความในคิวถึงปลายทางจำลองแล้ว');}
function sendMessage(text,attachment){text=text.trim();if(!text&&!attachment){toast('พิมพ์ข้อความก่อนส่งนะคะ');return;}const m={id:crypto.randomUUID?.()||String(Date.now()),peer:state.selected,mine:true,text,time:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}),status:'pending',hops:0,attachment};state.messages.push(m);persist();render();if(state.network==='offline'){toast('เก็บเข้าคิวแล้ว จะส่งเมื่อเชื่อมต่อจำลองได้');return;}m.status='sent';render();setTimeout(()=>{m.status='delivered';persist();log('รับ ACK จำลองสำหรับ '+m.id.slice(0,8));render();},900);}
document.addEventListener('click',async event=>{
 const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const [action,value]=el.dataset.action.split(':');
 if(action==='nav')navigate(value);
 else if(action==='chat'){state.selected=value;navigate('chat');}
 else if(action==='theme'){state.theme=state.theme==='dark'?'light':'dark';persist();render();}
 else if(action==='filter'){state.filter=value;render();}
 else if(action==='rescuer-filter'){state.rescuerFilter=value;render();}
 else if(action==='scan'){state.scanning=true;render();setTimeout(()=>{state.scanning=false;log('ค้นหาอุปกรณ์จำลองเสร็จ');render();toast(state.scenario==='empty'?'ยังไม่พบอุปกรณ์ในสถานการณ์นี้':state.scenario==='error'?'ตรวจสิทธิ์ก่อนค้นหาอีกครั้ง':'พบอุปกรณ์ตัวอย่าง 6 เครื่อง');},900);}
 else if(action==='permissions')modal('เชื่อมต่อได้ เมื่อสิทธิ์พร้อม','แอป Flutter จะขอ Bluetooth / อุปกรณ์ใกล้เคียง และตำแหน่งตามรุ่น Android เว็บต้นแบบนี้ไม่ขอสิทธิ์จริง คุณสามารถจำลองสถานะพร้อมใช้งานได้','จำลองว่าอนุญาตแล้ว',()=>{state.permissions=true;state.scenario='normal';render();toast('สถานะสิทธิ์จำลองพร้อมแล้ว');});
 else if(action==='notifications')modal('การแจ้งเตือนตัวอย่าง',`มีข้อความค้างส่ง ${pendingCount()} ข้อความ · ไม่มีการแจ้งเหตุฉุกเฉินจริง คุณสามารถตรวจคิวในหน้าคิวข้อความได้`);
 else if(action==='toggle'){state[value]=!state[value];persist();render();toast(state[value]?'เปิดโหมดหน่วยกู้ภัยจำลองแล้ว':'ปิดโหมดหน่วยกู้ภัยจำลองแล้ว');}
 else if(action==='network'){state.network=value;log('เปลี่ยนเครือข่ายจำลองเป็น '+value);render();toast('เปลี่ยนสถานะจำลองแล้ว');if(value!=='offline'&&pendingCount())await retryMessages(value==='online');}
 else if(action==='retry')await retryMessages();
 else if(action==='sync')await retryMessages(true);
 else if(action==='clear-log'){state.logs=[];render();toast('ล้างบันทึกจำลองแล้ว');}
 else if(action==='onboard-next'){if(state.onboard<2){state.onboard++;render();}else navigate('auth');}
 else if(action==='onboard-back'){state.onboard=Math.max(0,state.onboard-1);render();}
 else if(action==='logout')modal('ออกจากบัญชีจำลอง?','ประวัติตัวอย่างยังเก็บอยู่ในเบราว์เซอร์เครื่องนี้','ออกจากระบบ',()=>{state.loggedIn=false;persist();render();toast('ออกจากบัญชีจำลองแล้ว');});
 else if(action==='reset')modal('เริ่มต้นข้อมูลตัวอย่างใหม่?','ล้างประวัติและข้อมูลโปรไฟล์ที่กรอกในเว็บต้นแบบนี้เท่านั้น ไม่มีผลกับแอป Flutter','รีเซ็ตต้นแบบ',()=>{try{localStorage.removeItem(storageKey);}catch{}location.reload();});
 else if(action==='attach')$('#attachment')?.click();
 else if(action==='install'){if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;render();}else toast('ติดตั้งผ่านเมนูเบราว์เซอร์ เพิ่มไปยังหน้าจอหลัก');}
});
document.addEventListener('input',event=>{if(event.target.id==='chat-input')state.drafts[state.selected]=event.target.value;if(event.target.id==='sos-text')state.sosText=event.target.value;});
document.addEventListener('submit',event=>{event.preventDefault();const form=event.target;if(form.id==='chat-form'){const text=$('#chat-input').value;if(text.trim())state.drafts[state.selected]='';sendMessage(text);}else if(form.id==='profile-form'){const data=new FormData(form);state.profile={...state.profile,name:String(data.get('name')).trim()||'ผู้ใช้',contact:String(data.get('contact')),blood:String(data.get('blood')),medical:String(data.get('medical')),share:data.has('share')};persist();render();toast('บันทึกโปรไฟล์บนเครื่องนี้แล้ว');}else if(form.id==='auth-form'){const data=new FormData(form);state.profile.name=String(data.get('name')).trim()||'ผู้ใช้';state.profile.email=String(data.get('email'));state.loggedIn=true;persist();navigate('home');toast('เข้าสู่บัญชีจำลองแล้ว ไม่มีการเชื่อมต่อคลาวด์');}});
document.addEventListener('change',async event=>{
 if(event.target.id==='scenario'){state.scenario=event.target.value;render();}
 if(event.target.id==='attachment'){
  const file=event.target.files[0];if(!file)return;
  if(!/^(image|video)\//.test(file.type)){toast('เลือกไฟล์รูปภาพหรือวิดีโอเท่านั้น');return;}
  if(file.size>20*1024*1024){toast('ไฟล์ใหญ่เกิน 20 MB กรุณาเลือกไฟล์เล็กลง');return;}
  const video=file.type.startsWith('video');let blob=file;
  if(!video){try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.8));bitmap.close();}catch{toast('เปิดภาพไม่ได้ กรุณาเลือก JPEG หรือ PNG');return;}}
  const url=URL.createObjectURL(blob);modal(video?'พรีวิววิดีโอจำลอง':'พรีวิวรูปภาพจำลอง',`${video?'วิดีโอยังไม่บีบอัด':`ย่อภาพแล้ว ${Math.round(file.size/1024)} → ${Math.round(blob.size/1024)} KB`} · ${escapeHtml(file.name)}<br>สื่อจะอยู่เฉพาะเซสชันนี้และไม่ได้ส่งออกจากเครื่อง`,'เพิ่มในแชตจำลอง',()=>sendMessage(video?'วิดีโอตัวอย่าง':'รูปภาพตัวอย่าง',{url,type:video?'video':'image'}));
  const media=document.createElement(video?'video':'img');media.src=url;media.style.cssText='width:100%;max-height:220px;object-fit:contain;border-radius:12px;margin:12px 0';if(video)media.controls=true;else media.alt='ภาพก่อนเพิ่มในแชต';$('#modal').insertBefore(media,$('#modal p'));
 }
});
window.addEventListener('hashchange',()=>{const route=location.hash.slice(1);if(routeNames[route]&&route!==state.route){state.route=route;render();}});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;document.querySelectorAll('.install-btn').forEach(b=>b.classList.add('available'));});
window.addEventListener('online',()=>toast('เบราว์เซอร์กลับมาออนไลน์แล้ว · โหมดสาธิตยังเลือกได้ในหน้าเครือข่าย'));
window.addEventListener('offline',()=>toast('เบราว์เซอร์ออฟไลน์ · เปิดหน้าที่แคชไว้ได้'));
window.addEventListener('blur',cancelHold);
const initial=location.hash.slice(1);if(routeNames[initial])state.route=initial;
render();
if('serviceWorker' in navigator && (location.protocol==='https:' || ['localhost','127.0.0.1'].includes(location.hostname)))navigator.serviceWorker.register('./sw.js').catch(()=>toast('ติดตั้งแคชออฟไลน์ไม่สำเร็จ ลองโหลดหน้าใหม่เมื่อออนไลน์'));
